name: 'Setup Docker Compose on Windows/Linux/MacOS'
description: |
  Install Docker Compose with specified version, supports Linux, macOS, and Windows platforms.
inputs:
  version:
    description: 'Docker Compose version to install (defaults to latest version)'
    required: false
    default: 'latest'
outputs:
  docker-compose-version:
    description: 'The version of Docker Compose that was installed'
    value: ${{ steps.install-docker-compose.outputs.docker-compose-version }}
runs:
  using: "composite"
  steps:
    - name: Install Docker Compose
      id: install-docker-compose
      shell: bash
      env:
        DOCKER_COMPOSE_VERSION: ${{ inputs.version }}
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          script_path=$(cygpath -u "${{ github.action_path }}/scripts/install-docker-compose.sh")
          bash "$script_path"
        else
          bash "${{ github.action_path }}/scripts/install-docker-compose.sh"
        fi
