name: 'Setup Docker Compose'
description: 'Install Docker Compose with specified version'
inputs:
  version:
    description: 'Docker Compose version to install (defaults to latest version)'
    required: false
    default: 'latest'
outputs:
  docker-compose-version:
    description: 'The version of Docker Compose that was installed'
    value: ${{ steps.install-docker-compose.outputs.docker-compose-version }}
runs:
  using: "composite"
  steps:
    - name: Install Docker Compose
      id: install-docker-compose
      shell: bash
      env:
        DOCKER_COMPOSE_VERSION: ${{ inputs.version }}
      run: bash ./scripts/install-docker-compose.sh
